# Generated by Django 5.2.3 on 2025-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='disposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='quantity_liters',
            field=models.FloatField(default=0.0, help_text='Total quantity in liters'),
        ),
    ]
