# Generated by Django 5.2.3 on 2025-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_audit_disposed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='date',
            field=models.DateField(default='2007-11-07'),
        ),
    ]
