# Generated by Django 5.2.3 on 2025-06-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_audit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='AuditID',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
    ]
