# Generated by Django 5.2.3 on 2025-06-22 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_audit_auditid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='balances_calibrated_cleaned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='bio_sample_temp_maintained',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='biohazard_waste_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemical_containers_closed_and_disposed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemical_waste_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemicals_in_inventory',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemicals_stored_labelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='container_size',
            field=models.CharField(blank=True, help_text='E.g., 500ml, 1L, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='containers_free_from_leaks',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are containers free from leaks?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='containers_labeled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are containers labeled?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='containers_segregated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are containers segregated?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='audit',
            name='disposed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='disposed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='emergency_exits_inspected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='evidence_of_spills_or_expired_stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='fire_extinguishers_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='first_aid_kits_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='freezers_functional_clean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='glass_sharp_waste_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='hazard_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='hazardous_waste_generated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has hazardous waste been generated this week?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lab_coats_clean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lab_consumables_stock_ok',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lab_surfaces_clean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='microscopes_calibrated_cleaned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ppe_stocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='quantity_liters',
            field=models.FloatField(blank=True, default=0.0, help_text='Total quantity in liters', null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='remarks_or_corrective_action',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks/Corrective Action Taken'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='safety_data_sheets_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='secondary_containment_in_place',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is secondary containment in place?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='secondary_containment_ok',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='spill_kit_accessible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='spill_kits_stocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='storage_conditions_ok',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='storage_limit_exceeded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has the storage limit been exceeded?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='stored_in',
            field=models.CharField(blank=True, help_text='Storage location or cabinet', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='training_up_to_date',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='used_by',
            field=models.CharField(blank=True, help_text='Name of the person who used the chemical', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='used_for',
            field=models.CharField(blank=True, help_text='Purpose for which the chemical was used', max_length=100, null=True),
        ),
    ]
