# Generated by Django 5.2.3 on 2025-06-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_alter_audit_balances_calibrated_cleaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='location',
            field=models.CharField(blank=True, choices=[('KBD Fisheries Lab', 'KBD Fisheries Lab'), ('KBD Algae Lab', 'KBD Algae Lab'), ('KBD Aquaculture Lab', 'KBD Aquaculture Lab'), ('KBD Algae Facility Laboratory', 'KBD Algae Facility Laboratory'), ('Duba Lab', 'Duba Lab'), ('Jizan Lab', 'Jizan Lab'), ('Jubail Lab', 'Jubail Lab'), ('Al Raes Sea Cage Farms', 'Al Raes Sea Cage Farms'), ('Algae Facility Phase 2', 'Algae Facility Phase 2')], max_length=30, null=True),
        ),
    ]
