# Generated by Django 5.2.3 on 2025-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_audit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('chemical_waste', 'Hazardous Waste Log'), ('monthly', 'Monthly Inspection'), ('biannual', 'Biannual Environment Audit'), ('hazardous', 'Hazardous Waste Inspection')], default='monthly', max_length=20),
        ),
    ]
