# Generated by Django 5.2.3 on 2025-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_alter_audit_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='number_of_closeouts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='number_of_nonconformancies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
