# Generated by Django 5.2.3 on 2025-06-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_audit_number_of_closeouts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='number_of_nonconformancies',
            new_name='number_of_nonconformances',
        ),
    ]
