# Generated by Django 5.2.3 on 2025-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_rename_number_of_nonconformancies_audit_number_of_nonconformances'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='score',
            field=models.FloatField(blank=True, help_text='Automatically calculated percentage score for Monthly Inspections.', null=True, verbose_name='Inspection Score (%)'),
        ),
    ]
