# Generated by Django 5.2.3 on 2025-06-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_audit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='number_of_employees',
            field=models.IntegerField(blank=True, default=220, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='number_of_employees_trained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='number_of_inductions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('chemical_waste', 'Hazardous Waste Log'), ('monthly', 'Monthly Inspection'), ('biannual', 'Biannual Environment Audit'), ('hazardous', 'Hazardous Waste Inspection'), ('annual_refresher', 'Annual Environmental Refresher'), ('hse_induction', 'HSE Induction')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='audit',
            name='location',
            field=models.CharField(blank=True, choices=[('KBD Fisheries Lab', 'KBD Fisheries Lab'), ('KBD Algae Lab', 'KBD Algae Lab'), ('KBD Aquaculture Lab', 'KBD Aquaculture Lab'), ('KBD Algae Facility Laboratory', 'KBD Algae Facility Laboratory'), ('Duba Lab', 'Duba Lab'), ('Jizan Lab', 'Jizan Lab'), ('Jubail Lab', 'Jubail Lab'), ('Al Raes Sea Cage Farms', 'Al Raes Sea Cage Farms'), ('Algae Facility Phase 2', 'Algae Facility Phase 2')], max_length=100, null=True),
        ),
    ]
