# Generated by Django 5.2.3 on 2025-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_audit_number_of_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='details',
            field=models.TextField(blank=True, help_text='Details of the environmental incidents.', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='number_of_incidents',
            field=models.IntegerField(blank=True, default=0, help_text='Number of environmental incidents recorded.', null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('chemical_waste', 'Hazardous Waste Log'), ('monthly', 'Monthly Inspection'), ('biannual', 'Biannual Environment Audit'), ('hazardous', 'Hazardous Waste Inspection'), ('annual_refresher', 'Annual Environmental Refresher'), ('hse_induction', 'HSE Induction'), ('environmental_incidents', 'Environmental Incidents')], default='monthly', max_length=25),
        ),
    ]
