# Generated by Django 5.2.3 on 2025-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_audit_details_audit_number_of_incidents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='adequate_spill_kits_on_boats',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are adequate spill kits present on boats for handling emergencies?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='all_chemicals_have_manufacturer_labels',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check all chemicals have manufacturer labels?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='all_drums_containers_free_stagnant_water',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all drums and containers free from stagnant water?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='cages_secured_to_sea_bed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are the cages secured to the sea bed at all anchor points?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='chemical_inspection_monthly',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is chemical inspection carried out on a monthly basis?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='chemical_storage_room_proper_signage',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Check if chemical storage room has proper signage. Signage must say 'Chemical Storage Area' and include hazard warning."),
        ),
        migrations.AddField(
            model_name='audit',
            name='chemicals_lubricants_oils_secondary_containment',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all chemicals, lubricants, and oils stored in designated secondary containments?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='coshh_assessment_available_storage_location',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is COSHH assessment available at the storage location?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='coshh_register_valid_and_up_to_date',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the COSHH register valid and up to date?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='employees_trained_spcc_spill_response',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all employees trained on Spill Prevention Control and New Measures (SPCC) requirements and spill response?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='evaporation_pond_clean_and_well_maintained',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the evaporation pond clean and well-maintained?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='evaporation_pond_free_algal_growth_contamination',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the evaporation pond free from any visible algal growth or contamination?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='fuels_oils_hazardous_liquids_secondary_containment',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check if all fuels, oils and hazardous liquid chemicals are stored within secondary containment?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='general_waste_properly_managed_no_waste_lying_around',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is general waste properly managed, and is there no waste lying around the site?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='general_waste_properly_segregated_disposed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is general waste properly segregated and disposed of?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='hazardous_materials_properly_stored',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are hazardous materials stored properly with clear labels and SDS available?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='hazardous_waste_collected_stored_separately',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is hazardous waste collected and stored separately from general waste?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='hazardous_waste_containers_labeled_designated_areas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are hazardous waste containers properly labeled and stored in designated areas?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='log_maintained_reject_water_recycling',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there a log maintained for the reject water recycling process?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='material_storage_well_maintained',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are material storage areas well-maintained, free from contamination and pests?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='nets_checked_for_damage',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are nets checked for tears or damage to prevent fish escape?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='odours_from_site_operations',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are there any odours from the site operations?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='operations_minimal_disturbance',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all operations conducted with minimal disturbance to the surrounding environment?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='other_signs_pests_within_site',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are there any other signs of pests within the site?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='over_accumulation_fish_waste',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there any over accumulation of fish waste or unconsumed feed around the cages?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='record_environmental_incidents_past_week',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there a record of any environmental incidents (e.g., spills) from the past week?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='record_waste_collection_storage_disposal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there a record of waste collection, storage, and disposal?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='secondary_containment_structures_good_condition',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are secondary containment structures in good condition with no visible signs of leakage?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='significant_variations_water_quality',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are there any significant variations in water quality parameters from baseline values?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='signs_overflow_leakage_evaporation_pond',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are there any signs of overflow or leakage from the evaporation pond?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='spill_kit_available_storage_area',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there a spill kit available in the stoage area?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='spill_kits_available_stocked_accessible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are spill kits available, adequately stocked, and accessible?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='storage_containers_sealed_free_leaks',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are storage containers sealed and free from leaks?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='unusual_incidents_observations',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Were there any unusual incidents or observations during the inspection?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='visible_impact_on_marine_life',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there any visible impact on marine life outside the cage area?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='visible_mosquito_larvae_presence',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there any visible mosquito or larvae presence on site?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='visible_plume_emissions_spray_dryer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are there any visible plume emissions from the spray dryer when it is operational?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='waste_collection_areas_free_spills_leaks_contamination',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are waste collection areas free from spills, leaks, or contamination?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='waste_materials_properly_disposed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are waste materials (e.g., damaged nets, fish remains) being properly segregated and disposed?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='water_parameters_recorded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are water parameters (e.g., temperature, salinity, pH) being recorded at regular intervals?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='water_quality_evaporation_pond_acceptable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the water quality in the evaporation pond within acceptable parameters?'),
        ),
    ]
