# Generated by Django 5.2.3 on 2025-06-29 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0013_audit_adequate_spill_kits_on_boats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='The user who completed this audit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_audits', to=settings.AUTH_USER_MODEL, verbose_name='Completed By'),
        ),
    ]
