# Generated by Django 5.2.3 on 2025-06-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0014_audit_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='first_aid_kits_checked',
        ),
        migrations.AlterField(
            model_name='audit',
            name='balances_calibrated_cleaned',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Calibrate and clean balances'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='bio_sample_temp_maintained',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ensure biological sample storage (refrigerators/freezers) maintains required temperatures'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='biohazard_waste_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Review waste disposal containers; Biohazard waste'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemical_containers_closed_and_disposed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all chemical containers closed and empty containers labeled and disposed of appropriately?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemical_waste_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Review waste disposal containers; Chemical waste'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemicals_in_inventory',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all chemicals contained in the inventory?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='chemicals_stored_labelled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are all chemicals stored and labelled suitablt?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='emergency_exits_inspected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inspect emergency exits'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='evidence_of_spills_or_expired_stock',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Evidence of spills, expired chemical, or excessive stock?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='fire_extinguishers_checked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check fire extinguishers, and first aid kits'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='freezers_functional_clean',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ensure all freezers are clean and fonctionnal'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='glass_sharp_waste_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Review waste disposal containers; Glass, sharp waste'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lab_coats_clean',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check lab coat are clean'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lab_consumables_stock_ok',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Assess stock of lab consumables'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lab_surfaces_clean',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inspect lab surfaces and communal areas for cleanliness'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='microscopes_calibrated_cleaned',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Calibrate and clean microscopes'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ppe_stocked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ensure spill kits and PPE are stocked'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='safety_data_sheets_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are Safety Data sheets available?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='secondary_containment_ok',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is compatible secondary containment in place and in good condition'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='spill_kit_accessible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Spill kit stocked and accessible?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='spill_kits_stocked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ensure spill kits and PPE are stocked'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='storage_conditions_ok',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check storage conditions for chemicals and samples'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='training_up_to_date',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Check lab users training: Lab Safety Training, Hazardous Waste Training, Emergency and Incident Preparedness, Biosafety training, Animal Exposure Medical Evaluation, Annual Environmental Refresher (online), Incident Reporting Training (Online).'),
        ),
    ]
